# Generated by Django 3.2 on 2022-08-20 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_wishlist_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='size',
        ),
    ]
