# Generated by Django 3.2 on 2022-08-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220810_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='has_sizes',
            field=models.DecimalField(blank=True, decimal_places=2, default=False, max_digits=6, null=True),
        ),
    ]
