# Generated by Django 3.2 on 2022-08-20 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20220820_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_weight',
        ),
    ]
